# Generated by Django 5.2.3 on 2025-09-10 05:49

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=6)),
                ('branch', models.CharField(blank=True, choices=[('أدبي', 'الأدبي'), ('علمي', 'العلمي'), ('تاسع', 'الصف التاسع')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('student_number', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('tase3', models.IntegerField(blank=True, default=0)),
                ('disease', models.TextField(blank=True, default='none')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_job', models.CharField(blank=True, max_length=100)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_job', models.CharField(blank=True, max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=100)),
                ('elementary_school', models.CharField(blank=True, max_length=100)),
                ('how_knew_us', models.CharField(blank=True, choices=[('friend', 'صديق'), ('social', 'وسائل التواصل الاجتماعي'), ('ad', 'إعلان'), ('ads', 'إعلانات طرقية'), ('other', 'أخرى')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage discount (0-100)', max_digits=5, verbose_name='نسبة الحسم الافتراضي %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed amount discount', max_digits=10, verbose_name='قيمة الحسم الافتراضي')),
                ('discount_reason', models.CharField(blank=True, max_length=200, verbose_name='سبب الحسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='حساب الطالب (ذمم)')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإضافة بواسطة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['full_name'],
            },
        ),
    ]
