# Generated by Django 5.2.3 on 2025-09-10 05:49

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='رقم الهاتف')),
                ('branches', models.CharField(help_text='الفروع التي يدرسها المدرس (يمكن اختيار أكثر من فرع)', max_length=100, verbose_name='الفروع')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='أجر المدرس لكل ساعة تدريس', max_digits=10, null=True, verbose_name='أجر الساعة')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='الراتب الشهري الثابت (إن وجد)', max_digits=10, null=True, verbose_name='الراتب الشهري الثابت')),
                ('salary_type', models.CharField(choices=[('hourly', 'بالساعة'), ('monthly', 'شهري ثابت'), ('mixed', 'مختلط (ثابت + ساعات)')], default='hourly', max_length=20, verbose_name='نوع الراتب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'المدرسون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('admin', 'إداري'), ('accountant', 'محاسب'), ('mentor', 'موجه'), ('manager', 'مدير'), ('marketing', 'تسويق'), ('reception', 'استقبال')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_salary_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر دفع راتب')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('يومية', 'يومية'), ('طارئة', 'طارئة'), ('مرضية', 'مرضية')], max_length=20, verbose_name='نوع الإجازة')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الإجازة')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الإجازة')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاريخ تقديم الطلب')),
                ('is_replacement_secured', models.BooleanField(default=False, verbose_name='تم تأمين البديل')),
                ('manager_opinion', models.TextField(blank=True, null=True, verbose_name='رأي المدير')),
                ('general_manager_opinion', models.TextField(blank=True, null=True, verbose_name='رأي المدير العام')),
                ('status', models.CharField(choices=[('معلقة', 'معلقة'), ('موافق', 'موافق'), ('غير موافق', 'غير موافق')], default='معلقة', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='employ.employee')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['-created_at'],
            },
        ),
    ]
