# Generated by Django 5.2.3 on 2025-09-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccountlink',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to='students.student', verbose_name='الطالب / Student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='completion_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='accounts.journalentry', verbose_name='قيد الإكمال / Completion Entry'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.course', verbose_name='الدورة / Course'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='enrollment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='accounts.journalentry', verbose_name='قيد التسجيل / Enrollment Entry'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='الطالب / Student'),
        ),
        migrations.AddField(
            model_name='studentreceipt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.course', verbose_name='الدورة / Course'),
        ),
        migrations.AddField(
            model_name='studentreceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة / Created By'),
        ),
        migrations.AddField(
            model_name='studentreceipt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.studentenrollment', verbose_name='التسجيل / Enrollment'),
        ),
        migrations.AddField(
            model_name='studentreceipt',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry'),
        ),
        migrations.AddField(
            model_name='studentreceipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.student', verbose_name='الطالب / Student'),
        ),
        migrations.AddField(
            model_name='studentreceipt',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='students.student', verbose_name='ملف الطالب / Student Profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب / Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costcenter', verbose_name='مركز التكلفة / Cost Center'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('account', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'course')},
        ),
    ]
