# Generated by Django 5.0.6 on 2025-09-28 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_numbersequence_discountrule_ar_account_and_more'),
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeadvance',
            options={'ordering': ['-date'], 'verbose_name': 'سلفة الموظف / Employee Advance', 'verbose_name_plural': 'سلف الموظفين / Employee Advances'},
        ),
        migrations.AddField(
            model_name='employeeadvance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='employ.employee', verbose_name='الموظف / Employee'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='employ.employee', verbose_name='الموظف / Employee'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='employ.teacher', verbose_name='المعلم / Teacher'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموظف / Employee Name'),
        ),
    ]

