# Generated by Django 5.0.6 on 2025-09-28 06:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employeeadvance_options_and_more'),
        ('employ', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'ط§ظ„ط\xadط³ط§ط¨ / Account', 'verbose_name_plural': 'ط§ظ„ط\xadط³ط§ط¨ط§طھ / Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'ط§ظ„ظپطھط±ط© ط§ظ„ظ…ط\xadط§ط³ط¨ظٹط© / Accounting Period', 'verbose_name_plural': 'ط§ظ„ظپطھط±ط§طھ ط§ظ„ظ…ط\xadط§ط³ط¨ظٹط© / Accounting Periods'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'ط§ظ„ظ…ظٹط²ط§ظ†ظٹط© / Budget', 'verbose_name_plural': 'ط§ظ„ظ…ظٹط²ط§ظ†ظٹط§طھ / Budgets'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['code'], 'verbose_name': 'ظ…ط±ظƒط² ط§ظ„طھظƒظ„ظپط© / Cost Center', 'verbose_name_plural': 'ظ…ط±ط§ظƒط² ط§ظ„طھظƒظ„ظپط© / Cost Centers'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'ط§ظ„ط¯ظˆط±ط© / Course', 'verbose_name_plural': 'ط§ظ„ط¯ظˆط±ط§طھ / Courses'},
        ),
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['reason'], 'verbose_name': 'ظ‚ط§ط¹ط¯ط© ط§ظ„ط\xadط³ظ… / Discount Rule', 'verbose_name_plural': 'ظ‚ظˆط§ط¹ط¯ ط§ظ„ط\xadط³ظ… / Discount Rules'},
        ),
        migrations.AlterModelOptions(
            name='employeeadvance',
            options={'ordering': ['-date'], 'verbose_name': 'ط³ظ„ظپط© ط§ظ„ظ…ظˆط¸ظپ / Employee Advance', 'verbose_name_plural': 'ط³ظ„ظپ ط§ظ„ظ…ظˆط¸ظپظٹظ† / Employee Advances'},
        ),
        migrations.AlterModelOptions(
            name='expenseentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'ظ‚ظٹط¯ ط§ظ„ظ…طµط±ظˆظپ / Expense Entry', 'verbose_name_plural': 'ظ‚ظٹظˆط¯ ط§ظ„ظ…طµط±ظˆظپط§طھ / Expense Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'ظ‚ظٹط¯ ط§ظ„ظٹظˆظ…ظٹط© / Journal Entry', 'verbose_name_plural': 'ظ‚ظٹظˆط¯ ط§ظ„ظٹظˆظ…ظٹط© / Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'ط§ظ„ط·ط§ظ„ط¨ / Student', 'verbose_name_plural': 'ط§ظ„ط·ظ„ط§ط¨ / Students'},
        ),
        migrations.AlterModelOptions(
            name='studentaccountlink',
            options={'verbose_name': 'ط±ط¨ط· ط\xadط³ط§ط¨ ط§ظ„ط·ط§ظ„ط¨ / Student Account Link', 'verbose_name_plural': 'ط±ظˆط§ط¨ط· ط\xadط³ط§ط¨ط§طھ ط§ظ„ط·ظ„ط§ط¨ / Student Account Links'},
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'طھط³ط¬ظٹظ„ ط§ظ„ط·ط§ظ„ط¨ / Student Enrollment', 'verbose_name_plural': 'طھط³ط¬ظٹظ„ط§طھ ط§ظ„ط·ظ„ط§ط¨ / Student Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='studentreceipt',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'ط¥ظٹطµط§ظ„ ط§ظ„ط·ط§ظ„ط¨ / Student Receipt', 'verbose_name_plural': 'ط¥ظٹطµط§ظ„ط§طھ ط§ظ„ط·ظ„ط§ط¨ / Student Receipts'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'ط§ظ„ظ…ط¹ط§ظ…ظ„ط© / Transaction', 'verbose_name_plural': 'ط§ظ„ظ…ط¹ط§ظ…ظ„ط§طھ / Transactions'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'ط§ظ„ط£طµظˆظ„ / Assets'), ('LIABILITY', 'ط§ظ„ط®طµظˆظ… / Liabilities'), ('EQUITY', 'ط\xadظ‚ظˆظ‚ ط§ظ„ظ…ظ„ظƒظٹط© / Equity'), ('REVENUE', 'ط§ظ„ط¥ظٹط±ط§ط¯ط§طھ / Revenue'), ('EXPENSE', 'ط§ظ„ظ…طµط±ظˆظپط§طھ / Expenses')], max_length=20, verbose_name='ظ†ظˆط¹ ط§ظ„ط\xadط³ط§ط¨ / Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ط§ظ„ط±طµظٹط¯ / Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='ط±ظ…ط² ط§ظ„ط\xadط³ط§ط¨ / Account Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ط¯ظˆط±ط© / Course Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط· / Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_course_account',
            field=models.BooleanField(default=False, verbose_name='ط\xadط³ط§ط¨ ط¯ظˆط±ط© / Course Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student_account',
            field=models.BooleanField(default=False, verbose_name='ط\xadط³ط§ط¨ ط·ط§ظ„ط¨ / Student Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ط\xadط³ط§ط¨ / Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ظ„ط§ط³ظ… ط¨ط§ظ„ط¹ط±ط¨ظٹط© / Arabic Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.account', verbose_name='ط§ظ„ط\xadط³ط§ط¨ ط§ظ„ط£ط¨ / Parent Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ط·ط§ظ„ط¨ / Student Name'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظ‚ظپط§ظ„ / Closed At'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='ط£ظ‚ظپظ„ ط¨ظˆط§ط³ط·ط© / Closed By'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='end_date',
            field=models.DateField(verbose_name='طھط§ط±ظٹط® ط§ظ„ظ†ظ‡ط§ظٹط© / End Date'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='ظ…ظ‚ظپظ„ط© / Closed'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ط§ط³ظ… ط§ظ„ظپطھط±ط© / Period Name'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='start_date',
            field=models.DateField(verbose_name='طھط§ط±ظٹط® ط§ظ„ط¨ط¯ط§ظٹط© / Start Date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='ط§ظ„ط\xadط³ط§ط¨ / Account'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ظپط¹ظ„ظٹ / Actual Amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ظ…ط®ط·ط· / Budgeted Amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ / Notes'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountingperiod', verbose_name='ط§ظ„ظپطھط±ط© / Period'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='ط§ظ„ط±ظ…ط² / Code'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True, verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط· / Active'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ط§ظ„ط§ط³ظ… / Name'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='ط§ظ„ط§ط³ظ… ط¨ط§ظ„ط¹ط±ط¨ظٹط© / Arabic Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ط§ظ„ظ…ط¯ط© ط¨ط§ظ„ط³ط§ط¹ط§طھ / Duration (Hours)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط· / Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ط¯ظˆط±ط© / Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ظ„ط§ط³ظ… ط¨ط§ظ„ط¹ط±ط¨ظٹط© / Arabic Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ط³ط¹ط± / Price'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='description',
            field=models.TextField(blank=True, verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ظ‚ظٹظ…ط© ط§ظ„ط\xadط³ظ… ط§ظ„ط«ط§ط¨طھ / Fixed Discount Amount'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='ظ†ط³ط¨ط© ط§ظ„ط\xadط³ظ… % / Discount Percent'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط· / Active'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='reason',
            field=models.CharField(max_length=200, unique=True, verbose_name='ط³ط¨ط¨ ط§ظ„ط\xadط³ظ… / Discount Reason'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='reason_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ظ„ط³ط¨ط¨ ط¨ط§ظ„ط¹ط±ط¨ظٹط© / Reason in Arabic'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ / Amount'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ط£ظ†ط´ط¦ ط¨ظˆط§ط³ط·ط© / Created By'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='date',
            field=models.DateField(verbose_name='ط§ظ„طھط§ط±ظٹط® / Date'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='employ.employee', verbose_name='الموظف / Employee'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='employee_name',
            field=models.CharField(max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ظ…ظˆط¸ظپ / Employee Name'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='is_repaid',
            field=models.BooleanField(default=False, verbose_name='ظ…ط³ط¯ط¯ / Repaid'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='accounts.journalentry', verbose_name='ظ‚ظٹط¯ ط§ظ„ظٹظˆظ…ظٹط© / Journal Entry'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='purpose',
            field=models.CharField(max_length=500, verbose_name='ط§ظ„ط؛ط±ط¶ / Purpose'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='ط§ظ„ظ…ط±ط¬ط¹ / Reference'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ظ…ط³ط¯ط¯ / Repaid Amount'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='repayment_date',
            field=models.DateField(blank=True, null=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط³ط¯ط§ط¯ / Repayment Date'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ / Amount'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('SALARY', 'ط±ط§طھط¨ / Salary'), ('TEACHER_SALARY', 'ط±ط§طھط¨ ظ…ط¯ط±ط³ / Teacher Salary'), ('RENT', 'ط¥ظٹط¬ط§ط± / Rent'), ('UTILITIES', 'ظ…ط±ط§ظپظ‚ / Utilities'), ('SUPPLIES', 'ظ…ط³طھظ„ط²ظ…ط§طھ / Supplies'), ('MARKETING', 'طھط³ظˆظٹظ‚ / Marketing'), ('MAINTENANCE', 'طµظٹط§ظ†ط© / Maintenance'), ('SALARY', 'ط±ط§طھط¨ / Salary'), ('OTHER', 'ط£ط®ط±ظ‰ / Other')], max_length=20, verbose_name='ط§ظ„ظپط¦ط© / Category'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ط£ظ†ط´ط¦ ط¨ظˆط§ط³ط·ط© / Created By'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='date',
            field=models.DateField(verbose_name='ط§ظ„طھط§ط±ظٹط® / Date'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='description',
            field=models.CharField(max_length=500, verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='employ.employee', verbose_name='الموظف / Employee'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.journalentry', verbose_name='ظ‚ظٹط¯ ط§ظ„ظٹظˆظ…ظٹط© / Journal Entry'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ / Notes'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'ظ†ظ‚ط¯ / Cash'), ('BANK', 'ط¨ظ†ظƒ / Bank'), ('CARD', 'ط¨ط·ط§ظ‚ط© / Card'), ('TRANSFER', 'طھط\xadظˆظٹظ„ / Transfer')], default='CASH', max_length=20, verbose_name='ط·ط±ظٹظ‚ط© ط§ظ„ط¯ظپط¹ / Payment Method'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='ط±ظ‚ظ… ط§ظ„ظپط§طھظˆط±ط© / Receipt Number'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='ط§ظ„ظ…ط±ط¬ط¹ / Reference'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='employ.teacher', verbose_name='المعلم / Teacher'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ظ„ظ…ظˆط±ط¯ / Vendor'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ط£ظ†ط´ط¦ ط¨ظˆط§ط³ط·ط© / Created By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='ط§ظ„طھط§ط±ظٹط® / Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('MANUAL', 'ظٹط¯ظˆظٹ / Manual'), ('ENROLLMENT', 'طھط³ط¬ظٹظ„ / Enrollment'), ('PAYMENT', 'ط¯ظپط¹ / Payment'), ('COMPLETION', 'ط¥ظƒظ…ط§ظ„ / Completion'), ('EXPENSE', 'ظ…طµط±ظˆظپ / Expense'), ('ADJUSTMENT', 'طھط³ظˆظٹط© / Adjustment')], default='MANUAL', max_length=20, verbose_name='ظ†ظˆط¹ ط§ظ„ظ‚ظٹط¯ / Entry Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='ظ…ط±ط\xadظ„ / Posted'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='طھط§ط±ظٹط® ط§ظ„طھط±ط\xadظٹظ„ / Posted At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL, verbose_name='ط±ط\xadظ„ ط¨ظˆط§ط³ط·ط© / Posted By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='ط§ظ„ظ…ط±ط¬ط¹ / Reference'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ط¥ط¬ظ…ط§ظ„ظٹ / Total Amount'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='ط§ظ„ط¹ظ†ظˆط§ظ† / Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ط§ظ„ط¨ط±ظٹط¯ ط§ظ„ط¥ظ„ظƒطھط±ظˆظ†ظٹ / Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط· / Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ط§ظ„ط§ط³ظ… / Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ط§ظ„ظ‡ط§طھظپ / Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ط±ظ‚ظ… ط§ظ„ط·ط§ظ„ط¨ / Student ID'),
        ),
        migrations.AlterField(
            model_name='studentaccountlink',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_link', to='accounts.account', verbose_name='ط§ظ„ط\xadط³ط§ط¨ / Account'),
        ),
        migrations.AlterField(
            model_name='studentaccountlink',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to='students.student', verbose_name='ط§ظ„ط·ط§ظ„ط¨ / Student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظƒظ…ط§ظ„ / Completion Date'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='completion_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='accounts.journalentry', verbose_name='ظ‚ظٹط¯ ط§ظ„ط¥ظƒظ…ط§ظ„ / Completion Entry'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.course', verbose_name='ط§ظ„ط¯ظˆط±ط© / Course'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ظ‚ظٹظ…ط© ط§ظ„ط\xadط³ظ… / Discount Amount'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ظ†ط³ط¨ط© ط§ظ„ط\xadط³ظ… % / Discount Percent'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(verbose_name='طھط§ط±ظٹط® ط§ظ„طھط³ط¬ظٹظ„ / Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='accounts.journalentry', verbose_name='ظ‚ظٹط¯ ط§ظ„طھط³ط¬ظٹظ„ / Enrollment Entry'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='ظ…ظƒطھظ…ظ„ / Completed'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ / Notes'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'ظ†ظ‚ط¯ / Cash'), ('BANK', 'ط¨ظ†ظƒ / Bank'), ('CARD', 'ط¨ط·ط§ظ‚ط© / Card'), ('TRANSFER', 'طھط\xadظˆظٹظ„ / Transfer')], default='CASH', max_length=20, verbose_name='ط·ط±ظٹظ‚ط© ط§ظ„ط¯ظپط¹ / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='ط§ظ„ط·ط§ظ„ط¨ / Student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ط¥ط¬ظ…ط§ظ„ظٹ / Total Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ / Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.course', verbose_name='ط§ظ„ط¯ظˆط±ط© / Course'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ط¯ظˆط±ط© / Course Name'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ط£ظ†ط´ط¦ ط¨ظˆط§ط³ط·ط© / Created By'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='date',
            field=models.DateField(verbose_name='ط§ظ„طھط§ط±ظٹط® / Date'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ظ‚ظٹظ…ط© ط§ظ„ط\xadط³ظ… / Discount Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ظ†ط³ط¨ط© ط§ظ„ط\xadط³ظ… % / Discount Percent'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.studentenrollment', verbose_name='ط§ظ„طھط³ط¬ظٹظ„ / Enrollment'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='ظ…ط·ط¨ظˆط¹ / Printed'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounts.journalentry', verbose_name='ظ‚ظٹط¯ ط§ظ„ظٹظˆظ…ظٹط© / Journal Entry'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ / Notes'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ظ…ط¯ظپظˆط¹ / Paid Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'ظ†ظ‚ط¯ / Cash'), ('BANK', 'ط¨ظ†ظƒ / Bank'), ('CARD', 'ط¨ط·ط§ظ‚ط© / Card'), ('TRANSFER', 'طھط\xadظˆظٹظ„ / Transfer')], default='CASH', max_length=20, verbose_name='ط·ط±ظٹظ‚ط© ط§ظ„ط¯ظپط¹ / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='ط±ظ‚ظ… ط§ظ„ط¥ظٹطµط§ظ„ / Receipt Number'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.student', verbose_name='ط§ظ„ط·ط§ظ„ط¨ / Student'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='student_name',
            field=models.CharField(max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ط·ط§ظ„ط¨ / Student Name'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='students.student', verbose_name='ظ…ظ„ظپ ط§ظ„ط·ط§ظ„ط¨ / Student Profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='ط§ظ„ط\xadط³ط§ط¨ / Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ / Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costcenter', verbose_name='ظ…ط±ظƒط² ط§ظ„طھظƒظ„ظپط© / Cost Center'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='ط§ظ„ظˆطµظپ / Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_debit',
            field=models.BooleanField(verbose_name='ظ…ط¯ظٹظ† / Debit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.journalentry', verbose_name='ظ‚ظٹط¯ ط§ظ„ظٹظˆظ…ظٹط© / Journal Entry'),
        ),
    ]
