# Generated by Django 5.0.6 on 2025-09-28 08:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_accountingperiod_options_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'ط§ظ„طط³ط§ط¨ / Account', 'verbose_name_plural': 'ط§ظ„طط³ط§ط¨ط§طھ / Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'ط§ظ„ظپطھط±ط© ط§ظ„ظ…طط§ط³ط¨ظٹط© / Accounting Period', 'verbose_name_plural': 'ط§ظ„ظپطھط±ط§طھ ط§ظ„ظ…طط§ط³ط¨ظٹط© / Accounting Periods'},
        ),
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['reason'], 'verbose_name': 'ظ‚ط§ط¹ط¯ط© ط§ظ„طط³ظ… / Discount Rule', 'verbose_name_plural': 'ظ‚ظˆط§ط¹ط¯ ط§ظ„طط³ظ… / Discount Rules'},
        ),
        migrations.AlterModelOptions(
            name='studentaccountlink',
            options={'verbose_name': 'ط±ط¨ط· طط³ط§ط¨ ط§ظ„ط·ط§ظ„ط¨ / Student Account Link', 'verbose_name_plural': 'ط±ظˆط§ط¨ط· طط³ط§ط¨ط§طھ ط§ظ„ط·ظ„ط§ط¨ / Student Account Links'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'ط§ظ„ط£طµظˆظ„ / Assets'), ('LIABILITY', 'ط§ظ„ط®طµظˆظ… / Liabilities'), ('EQUITY', 'طظ‚ظˆظ‚ ط§ظ„ظ…ظ„ظƒظٹط© / Equity'), ('REVENUE', 'ط§ظ„ط¥ظٹط±ط§ط¯ط§طھ / Revenue'), ('EXPENSE', 'ط§ظ„ظ…طµط±ظˆظپط§طھ / Expenses')], max_length=20, verbose_name='نوع الحساب / Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد / Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب / Account Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الدورة / Course Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط / Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_course_account',
            field=models.BooleanField(default=False, verbose_name='حساب الدورة / Course Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student_account',
            field=models.BooleanField(default=False, verbose_name='حساب الطالب / Student Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الحساب / Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربية / Arabic Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.account', verbose_name='الحساب الأب / Parent Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الطالب / Student Name'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال / Closed At'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='أُقفل بواسطة / Closed By'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ النهاية / End Date'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='مقفلة / Closed'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفترة / Period Name'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية / Start Date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب / Account'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ الفعلي / Actual Amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المخطط / Budgeted Amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات / Notes'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountingperiod', verbose_name='الفترة / Period'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط / Active'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم / Name'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربية / Arabic Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالساعات / Duration (Hours)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط / Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الدورة / Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربية / Arabic Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر / Price'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قيمة الخصم الثابت / Fixed Discount Amount'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الخصم % / Discount Percent'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط / Active'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='reason',
            field=models.CharField(max_length=200, unique=True, verbose_name='سبب الخصم / Discount Reason'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='reason_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='السبب بالعربية / Reason in Arabic'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ / Amount'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة / Created By'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='date',
            field=models.DateField(verbose_name='التاريخ / Date'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='employee_name',
            field=models.CharField(max_length=200, verbose_name='اسم الموظف / Employee Name'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='is_repaid',
            field=models.BooleanField(default=False, verbose_name='مسدد / Repaid'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='purpose',
            field=models.CharField(max_length=500, verbose_name='الغرض / Purpose'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='المرجع / Reference'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المسدد / Repaid Amount'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='repayment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ السداد / Repayment Date'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ / Amount'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('SALARY', 'ط±ط§طھط¨ / Salary'), ('TEACHER_SALARY', 'ط±ط§طھط¨ ظ…ط¯ط±ط³ / Teacher Salary'), ('RENT', 'ط¥ظٹط¬ط§ط± / Rent'), ('UTILITIES', 'ظ…ط±ط§ظپظ‚ / Utilities'), ('SUPPLIES', 'ظ…ط³طھظ„ط²ظ…ط§طھ / Supplies'), ('MARKETING', 'طھط³ظˆظٹظ‚ / Marketing'), ('MAINTENANCE', 'طµظٹط§ظ†ط© / Maintenance'), ('SALARY', 'ط±ط§طھط¨ / Salary'), ('OTHER', 'ط£ط®ط±ظ‰ / Other')], max_length=20, verbose_name='الفئة / Category'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة / Created By'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='date',
            field=models.DateField(verbose_name='التاريخ / Date'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='description',
            field=models.CharField(max_length=500, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات / Notes'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'ظ†ظ‚ط¯ / Cash'), ('BANK', 'ط¨ظ†ظƒ / Bank'), ('CARD', 'ط¨ط·ط§ظ‚ط© / Card'), ('TRANSFER', 'طھطظˆظٹظ„ / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الإيصال / Receipt Number'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='المرجع / Reference'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='المورد / Vendor'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة / Created By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='التاريخ / Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('MANUAL', 'ظٹط¯ظˆظٹ / Manual'), ('ENROLLMENT', 'طھط³ط¬ظٹظ„ / Enrollment'), ('PAYMENT', 'ط¯ظپط¹ / Payment'), ('COMPLETION', 'ط¥ظƒظ…ط§ظ„ / Completion'), ('EXPENSE', 'ظ…طµط±ظˆظپ / Expense'), ('ADJUSTMENT', 'طھط³ظˆظٹط© / Adjustment')], default='MANUAL', max_length=20, verbose_name='نوع القيد / Entry Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='مُرحل / Posted'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل / Posted At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL, verbose_name='مُرحل بواسطة / Posted By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='المرجع / Reference'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الإجمالي / Total Amount'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان / Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني / Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط / Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم / Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف / Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الطالب / Student ID'),
        ),
        migrations.AlterField(
            model_name='studentaccountlink',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_link', to='accounts.account', verbose_name='الحساب / Account'),
        ),
        migrations.AlterField(
            model_name='studentaccountlink',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to='students.student', verbose_name='الطالب / Student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال / Completion Date'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='completion_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='accounts.journalentry', verbose_name='قيد الإكمال / Completion Entry'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.course', verbose_name='الدورة / Course'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم / Discount Amount'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم % / Discount Percent'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(verbose_name='تاريخ التسجيل / Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='accounts.journalentry', verbose_name='قيد التسجيل / Enrollment Entry'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='مكتمل / Completed'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات / Notes'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'ظ†ظ‚ط¯ / Cash'), ('BANK', 'ط¨ظ†ظƒ / Bank'), ('CARD', 'ط¨ط·ط§ظ‚ط© / Card'), ('TRANSFER', 'طھطظˆظٹظ„ / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='الطالب / Student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي / Total Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ / Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.course', verbose_name='الدورة / Course'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الدورة / Course Name'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة / Created By'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='date',
            field=models.DateField(verbose_name='التاريخ / Date'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم / Discount Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم % / Discount Percent'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.studentenrollment', verbose_name='التسجيل / Enrollment'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='مطبوع / Printed'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات / Notes'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع / Paid Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'ظ†ظ‚ط¯ / Cash'), ('BANK', 'ط¨ظ†ظƒ / Bank'), ('CARD', 'ط¨ط·ط§ظ‚ط© / Card'), ('TRANSFER', 'طھطظˆظٹظ„ / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الإيصال / Receipt Number'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.student', verbose_name='الطالب / Student'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='student_name',
            field=models.CharField(max_length=200, verbose_name='اسم الطالب / Student Name'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='students.student', verbose_name='ملف الطالب / Student Profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب / Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ / Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costcenter', verbose_name='مركز التكلفة / Cost Center'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_debit',
            field=models.BooleanField(verbose_name='مدين / Debit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry'),
        ),
    ]
