# Generated by Django 5.0.6 on 2025-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_options_alter_accountingperiod_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'الطساب / Account', 'verbose_name_plural': 'الطسابات / Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'الفترة المطاسبية / Accounting Period', 'verbose_name_plural': 'الفترات المطاسبية / Accounting Periods'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'الميزانية / Budget', 'verbose_name_plural': 'الميزانيات / Budgets'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['code'], 'verbose_name': 'مركز التكلفة / Cost Center', 'verbose_name_plural': 'مراكز التكلفة / Cost Centers'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'الدورة / Course', 'verbose_name_plural': 'الدورات / Courses'},
        ),
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['reason'], 'verbose_name': 'قاعدة الطسم / Discount Rule', 'verbose_name_plural': 'قواعد الطسم / Discount Rules'},
        ),
        migrations.AlterModelOptions(
            name='employeeadvance',
            options={'ordering': ['-date'], 'verbose_name': 'سلفة الموظف / Employee Advance', 'verbose_name_plural': 'سلف الموظفين / Employee Advances'},
        ),
        migrations.AlterModelOptions(
            name='expenseentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'قيد المصروف / Expense Entry', 'verbose_name_plural': 'قيود المصروفات / Expense Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'قيد اليومية / Journal Entry', 'verbose_name_plural': 'قيود اليومية / Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'الطالب / Student', 'verbose_name_plural': 'الطلاب / Students'},
        ),
        migrations.AlterModelOptions(
            name='studentaccountlink',
            options={'verbose_name': 'ربط طساب الطالب / Student Account Link', 'verbose_name_plural': 'روابط طسابات الطلاب / Student Account Links'},
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'تسجيل الطالب / Student Enrollment', 'verbose_name_plural': 'تسجيلات الطلاب / Student Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='studentreceipt',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'إيصال الطالب / Student Receipt', 'verbose_name_plural': 'إيصالات الطلاب / Student Receipts'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'المعاملة / Transaction', 'verbose_name_plural': 'المعاملات / Transactions'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'الأصول / Assets'), ('LIABILITY', 'الخصوم / Liabilities'), ('EQUITY', 'طقوق الملكية / Equity'), ('REVENUE', 'الإيرادات / Revenue'), ('EXPENSE', 'المصروفات / Expenses')], max_length=20, verbose_name='نوع الحساب / Account Type'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('SALARY', 'راتب / Salary'), ('TEACHER_SALARY', 'راتب مدرس / Teacher Salary'), ('RENT', 'إيجار / Rent'), ('UTILITIES', 'مرافق / Utilities'), ('SUPPLIES', 'مستلزمات / Supplies'), ('MARKETING', 'تسويق / Marketing'), ('MAINTENANCE', 'صيانة / Maintenance'), ('SALARY', 'راتب / Salary'), ('OTHER', 'أخرى / Other')], max_length=20, verbose_name='الفئة / Category'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد / Cash'), ('BANK', 'بنك / Bank'), ('CARD', 'بطاقة / Card'), ('TRANSFER', 'تطويل / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('MANUAL', 'يدوي / Manual'), ('ENROLLMENT', 'تسجيل / Enrollment'), ('PAYMENT', 'دفع / Payment'), ('COMPLETION', 'إكمال / Completion'), ('EXPENSE', 'مصروف / Expense'), ('ADJUSTMENT', 'تسوية / Adjustment')], default='MANUAL', max_length=20, verbose_name='نوع القيد / Entry Type'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد / Cash'), ('BANK', 'بنك / Bank'), ('CARD', 'بطاقة / Card'), ('TRANSFER', 'تطويل / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد / Cash'), ('BANK', 'بنك / Bank'), ('CARD', 'بطاقة / Card'), ('TRANSFER', 'تطويل / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
    ]
