# Generated by Django 5.2.3 on 2025-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('subject_type', models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي'), ('ninth', 'تاسع'), ('common', 'مشترك')], max_length=10, verbose_name='نوع المادة')),
                ('teachers', models.ManyToManyField(related_name='subjects_taught', to='employ.teacher', verbose_name='المدرسون')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['name'],
            },
        ),
    ]
