# Generated by Django 5.2.3 on 2025-09-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='الشعبة 1', max_length=50, verbose_name='اسم الشعبة')),
                ('class_type', models.CharField(choices=[('study', 'شعبة دراسية'), ('course', 'دورة')], default='study', max_length=10, verbose_name='نوع الشعبة')),
                ('branches', models.CharField(blank=True, choices=[('أدبي', 'الأدبي'), ('علمي', 'العلمي'), ('تاسع', 'الصف التاسع')], max_length=100, null=True, verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'شعبة',
                'verbose_name_plural': 'شعب',
            },
        ),
        migrations.CreateModel(
            name='Classroomenrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مادة الشعبة',
                'verbose_name_plural': 'مواد الشعب',
                'unique_together': {('classroom', 'subject')},
            },
        ),
    ]
